### ISSUE TITLE
Add alternative to std::sync::{Once, OnceLock}

### ISSUE THREAD

**Issue by RReverser** [DouglasDwyer/wasm_sync#1]
`Once` is internally implemented via `futex_wait`, which will also call into `atomics.wait`: https://github.com/rust-lang/rust/blob/1ead4761e9e2f056385768614c23ffa7acb6a19e/library/std/src/sys_common/once/futex.rs#L138

`OnceLock` is similar and both will need an alternative that uses a spin-lock instead.

**Comment by RReverser** [comment]
Maybe it's best to rebase this crate to use [spin](https://docs.rs/spin/latest/spin/) under the hood which already has alternatives to all these primitives, but doesn't have a `std`-compatible API. `wasm_sync` could be a bridge between the implementation and std-like API.

**Comment by DouglasDwyer** [comment]
Good idea! I will take care of this when I find some time - a PR is also welcome if you'd like.

I don't really think that `spin` would fit with this crate's goals. The `spin` primitives _always_ spin when you try to lock them - but the primitives in this library *will atomic wait in web workers*. This library only spins on the main browser thread.

**Comment by RReverser** [comment]
Right, but that's why I mentioned this crate could be wrapping it - so, under the hood, it would switch between spin and std (atomic wait) implementations depending on whether or not it's running on the main thread.

**Comment by DouglasDwyer** [comment]
I apologize, but I don't quite understand how that would work. What if the main thread and a worker thread try to wait on the same `wasm_sync::Mutex`? If they are using two different primitives under the hood (a `std::Mutex` or a `spin::Mutex`) how would one thread know to wait for the other?

**Comment by RReverser** [comment]
🤦🏼‍♂️ You're right, of course, that won't work.

**Comment by DouglasDwyer** [comment]
I've gone ahead and implemented `Once` and `OnceLock`. Please let me know if you run into issues with them!

**Comment by RReverser** [comment]
Nice, thanks!

**Comment by RReverser** [comment]
Btw, not sure if you saw the ping the other day, but this repo now powers Rayon on Wasm (via rayon + wasm-bindgen-rayon) :)

**Comment by DouglasDwyer** [comment]
I did! I'm pleased to be a part of such an integral library.
